AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
